// This file has been generated by Specta. Do not edit this file manually.
export type AccessibilityNotification = {
	notification: number,
	event: JsonValue,
};

export type Action = Action_Serialize | Action_Deserialize;

export type Action_Deserialize = string;

export type Action_Serialize = 
/**  An action referenced by name, for actions not in the predefined list. */
{ literal: string } | "press" | "increment" | "decrement" | "confirm" | "cancel" | "showAlternateUI" | "showDefaultUI" | "raise" | "showMenu" | "pick";

export type AppHandle = number;

export type Attribute = Attribute_Serialize | Attribute_Deserialize;

export type Attribute_Deserialize = string;

export type Attribute_Serialize = 
/**  An attribute referenced by name, for attributes not in the predefined list. */
{ literal: string } | "identifier" | "role" | "subrole" | "roleDescription" | "title" | "description" | "help" | "parent" | "children" | "selectedChildren" | "visibleChildren" | "window" | "topLevelUIElement" | "titleUIElement" | "servesAsTitleForUIElements" | "linkedUIElements" | "sharedFocusElements" | "enabled" | "focused" | "position" | "size" | "value" | "valueDescription" | "minValue" | "maxValue" | "valueIncrement" | "valueWraps" | "allowedValues" | "placeholderValue" | "selectedText" | "selectedTextRange" | "selectedTextRanges" | "visibleCharacterRange" | "numberOfCharacters" | "sharedTextUIElements" | "sharedCharacterRange" | "main" | "minimized" | "closeButton" | "zoomButton" | "minimizeButton" | "toolbarButton" | "proxy" | "growArea" | "modal" | "defaultButton" | "cancelButton" | "menuItemCmdChar" | "menuItemCmdVirtualKey" | "menuItemCmdGlyph" | "menuItemCmdModifiers" | "menuItemMarkChar" | "menuItemPrimaryUIElement" | "menuBar" | "windows" | "frontmost" | "hidden" | "mainWindow" | "focusedWindow" | "focusedUIElement" | "extrasMenuBar" | "hourField" | "minuteField" | "secondField" | "ampmField" | "dayField" | "monthField" | "yearField" | "rows" | "visibleRows" | "selectedRows" | "columns" | "visibleColumns" | "selectedColumns" | "sortDirection" | "columnHeaderUIElements" | "index" | "disclosing" | "disclosedRows" | "disclosedByRow" | "matteHole" | "matteContentUIElement" | "markerUIElements" | "units" | "unitDescription" | "markerType" | "markerTypeDescription" | "horizontalScrollBar" | "verticalScrollBar" | "orientation" | "header" | "edited" | "tabs" | "overflowButton" | "filename" | "expanded" | "selected" | "splitters" | "contents" | "nextContents" | "previousContents" | "document" | "incrementor" | "decrementButton" | "incrementButton" | "columnTitle" | "url" | "labelUIElements" | "labelValue" | "shownMenuUIElement" | "isApplicationRunning" | "focusedApplication" | "elementBusy" | "alternateUIVisible";

export type ElementHandle = number;

export type EndFunction = {
	function: Function,
};

export type Filter = 
/**  Matches if the element's ElementBusy attribute is equal to the given boolean */
({ elementBusy: boolean }) & { description?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Enabled attribute is equal to the given boolean */
({ enabled: boolean }) & { description?: never; elementBusy?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Focused attribute is equal to the given boolean */
({ focused: boolean }) & { description?: never; elementBusy?: never; enabled?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Frontmost attribute is equal to the given boolean */
({ frontmost: boolean }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Main attribute is equal to the given boolean */
({ main: boolean }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Minimized attribute is equal to the given boolean */
({ minimized: boolean }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Description attribute is equal to the given string */
({ description: MatchString }) & { elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Help attribute is equal to the given string */
({ help: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Identifier attribute is equal to the given string */
({ identifier: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's LabelValue attribute is equal to the given string */
({ labelValue: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's PlaceholderValue attribute is equal to the given string */
({ placeholderValue: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Role attribute is equal to the given string */
({ role: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's RoleDescription attribute is equal to the given string */
({ roleDescription: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Subrole attribute is equal to the given string */
({ subrole: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's Title attribute is equal to the given string */
({ title: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; value?: never; valueDescription?: never } | 
/**  Matches if the element's ValueDescription attribute is equal to the given string */
({ valueDescription: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never } | 
/**  Matches if the element's Value attribute is equal to the given string */
({ value: MatchString }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; has?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; valueDescription?: never } | 
/**  Matches if any of the element's children match the FilterTree. Expensive operation. */
({ has: Filter[] }) & { description?: never; elementBusy?: never; enabled?: never; focused?: never; frontmost?: never; help?: never; identifier?: never; labelValue?: never; main?: never; minimized?: never; placeholderValue?: never; role?: never; roleDescription?: never; subrole?: never; title?: never; value?: never; valueDescription?: never } | 
/**  Always matches. Useful for grabbing the first element that's being checked. */
"any";

export type Function = number;

/**  pack → host */
export type HostHandlers = HostHandlers_Serialize | HostHandlers_Deserialize;

/**  pack → host */
export type HostHandlers_Deserialize = ({ registerApp: {
	bundleIdentifier: string,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ defineFunction: {
	functionName: string,
	view: View,
} }) & { declareVar?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ declareVar: {
	name: string,
} }) & { defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ setVar: {
	var: number,
	value: boolean,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; unobserveElementNotification?: never; walkElement?: never } | ({ runFunction: {
	publisherDomain: string,
	packName: string,
	functionName: string,
	payload: JsonValue,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | 
/**
 *  The pack finished its initial module load and function registration; it is
 *  now safe to run the functions it declared.
 */
({ ready: Record<string, never> }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ keyboardKeyDown: {
	app: AppHandle,
	key: Key_Deserialize | null,
	modifiers: Modifiers,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ keyboardKeyUp: {
	app: AppHandle,
	key: Key_Deserialize | null,
	modifiers: Modifiers,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ keyboardKeyPress: {
	app: AppHandle,
	key: Key_Deserialize | null,
	modifiers: Modifiers,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ scrollWheelY: {
	app: AppHandle,
	delta: number,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ scrollWheelX: {
	app: AppHandle,
	delta: number,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ getAppElement: {
	app: AppHandle,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ walkElement: {
	root: ElementHandle,
	filterPath: Filter[][],
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never } | ({ disposeElement: {
	element: ElementHandle,
} }) & { declareVar?: never; defineFunction?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ performElementAction: {
	element: ElementHandle,
	action: Action_Deserialize,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ getElementAttribute: {
	element: ElementHandle,
	attribute: Attribute_Deserialize,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ setElementAttribute: {
	element: ElementHandle,
	attribute: Attribute_Deserialize,
	value: SetAttributeValue,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ observeElementNotification: {
	element: ElementHandle,
	notificationName: Notification,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ unobserveElementNotification: {
	notification: number,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; walkElement?: never };

/**  pack → host */
export type HostHandlers_Serialize = ({ registerApp: {
	bundleIdentifier: string,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ defineFunction: {
	functionName: string,
	view: View,
} }) & { declareVar?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ declareVar: {
	name: string,
} }) & { defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ setVar: {
	var: number,
	value: boolean,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; unobserveElementNotification?: never; walkElement?: never } | ({ runFunction: {
	publisherDomain: string,
	packName: string,
	functionName: string,
	payload: JsonValue,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | 
/**
 *  The pack finished its initial module load and function registration; it is
 *  now safe to run the functions it declared.
 */
({ ready: Record<string, never> }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ keyboardKeyDown: {
	app: AppHandle,
	key: Key_Serialize | null,
	modifiers: Modifiers,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ keyboardKeyUp: {
	app: AppHandle,
	key: Key_Serialize | null,
	modifiers: Modifiers,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ keyboardKeyPress: {
	app: AppHandle,
	key: Key_Serialize | null,
	modifiers: Modifiers,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ scrollWheelY: {
	app: AppHandle,
	delta: number,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ scrollWheelX: {
	app: AppHandle,
	delta: number,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ getAppElement: {
	app: AppHandle,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ walkElement: {
	root: ElementHandle,
	filterPath: Filter[][],
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never } | ({ disposeElement: {
	element: ElementHandle,
} }) & { declareVar?: never; defineFunction?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ performElementAction: {
	element: ElementHandle,
	action: Action_Serialize,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ getElementAttribute: {
	element: ElementHandle,
	attribute: Attribute_Serialize,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ setElementAttribute: {
	element: ElementHandle,
	attribute: Attribute_Serialize,
	value: SetAttributeValue,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ observeElementNotification: {
	element: ElementHandle,
	notificationName: Notification,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; unobserveElementNotification?: never; walkElement?: never } | ({ unobserveElementNotification: {
	notification: number,
} }) & { declareVar?: never; defineFunction?: never; disposeElement?: never; getAppElement?: never; getElementAttribute?: never; keyboardKeyDown?: never; keyboardKeyPress?: never; keyboardKeyUp?: never; observeElementNotification?: never; performElementAction?: never; ready?: never; registerApp?: never; runFunction?: never; scrollWheelX?: never; scrollWheelY?: never; setElementAttribute?: never; setVar?: never; walkElement?: never };

/**
 *  Binding-only mirror of an opaque JSON value. The wire/Rust type stays
 *  `serde_json::Value`; the opaque proto fields carry `#[specta(type = JsonValue)]`
 *  so only the *generated* type changes — a recursive JSON value whose numbers are
 *  `f64` (→ TS `number`). This sidesteps specta's bigint-forbid on `serde_json::Number`'s
 *  `i64`/`u64`, and stays exporter-neutral (no TypeScript-only `unknown` marker leaks
 *  into the contract). Never (de)serialized itself.
 */
export type JsonValue = boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

export type Key = Key_Serialize | Key_Deserialize;

export type Key_Deserialize = "f1" | "f2" | "f3" | "f4" | "f5" | "f6" | "f7" | "f8" | "f9" | "f10" | "f11" | "f12" | "f13" | "f14" | "f15" | "f16" | "f17" | "f18" | "f19" | "f20" | "escape" | "esc" | "delete" | "tab" | "capsLock" | "caps" | "alphaShift" | "return" | "space" | "leftArrow" | "left" | "rightArrow" | "right" | "upArrow" | "up" | "downArrow" | "down" | "pageUp" | "pageDown" | "home" | "end" | "leftShift" | "shift" | "rightShift" | "leftControl" | "control" | "ctrl" | "rightControl" | "rightCtrl" | "leftOption" | "option" | "alternate" | "opt" | "alt" | "rightOption" | "leftCommand" | "command" | "cmd" | "rightCommand" | "rightCmd" | "globe" | "fn" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "1" | "num1" | "2" | "num2" | "3" | "num3" | "4" | "num4" | "5" | "num5" | "6" | "num6" | "7" | "num7" | "8" | "num8" | "9" | "num9" | "0" | "num0" | "grave" | "~" | "`" | "backtick" | "leftBracket" | "{" | "[" | "rightBracket" | "}" | "]" | "backslash" | "|" | "\\" | "semicolon" | ":" | ";" | "quote" | "'" | "\"" | "minus" | "-" | "_" | "equal" | "+" | "=" | "comma" | "<" | "," | "period" | ">" | "." | "slash" | "?" | "/" | "section" | "§" | "intlBackslash" | "internationalBackslash" | "intl\\" | "numpad0" | "numpad1" | "numpad2" | "numpad3" | "numpad4" | "numpad5" | "numpad6" | "numpad7" | "numpad8" | "numpad9" | "numpadMultiply" | "numpadAdd" | "numpadSubtract" | "numpadDivide" | "numpadEnter" | "numpadDecimal" | "numpadClear" | "numpadComma" | "volumeUp" | "volumeDown" | "mute" | "yen" | "underscore" | "eisu" | "kana" | "menu" | "help" | "forwardDelete" | "power" | "missionControl" | "enterPowerbook";

export type Key_Serialize = "f1" | "f2" | "f3" | "f4" | "f5" | "f6" | "f7" | "f8" | "f9" | "f10" | "f11" | "f12" | "f13" | "f14" | "f15" | "f16" | "f17" | "f18" | "f19" | "f20" | "escape" | "delete" | "tab" | "capsLock" | "return" | "space" | "leftArrow" | "rightArrow" | "upArrow" | "downArrow" | "pageUp" | "pageDown" | "home" | "end" | "leftShift" | "rightShift" | "leftControl" | "rightControl" | "leftOption" | "rightOption" | "leftCommand" | "rightCommand" | "globe" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "0" | "grave" | "leftBracket" | "rightBracket" | "backslash" | "semicolon" | "quote" | "minus" | "equal" | "comma" | "period" | "slash" | "section" | "numpad0" | "numpad1" | "numpad2" | "numpad3" | "numpad4" | "numpad5" | "numpad6" | "numpad7" | "numpad8" | "numpad9" | "numpadMultiply" | "numpadAdd" | "numpadSubtract" | "numpadDivide" | "numpadEnter" | "numpadDecimal" | "numpadClear" | "numpadComma" | "volumeUp" | "volumeDown" | "mute" | "yen" | "underscore" | "eisu" | "kana" | "menu" | "help" | "forwardDelete" | "power" | "missionControl" | "enterPowerbook";

export type MatchString = 
/**  Wildcard pattern matching. `?` matches any single character, `*` matches any sequence. */
({ glob: string }) & { literal?: never } | 
/**  Exact identity match. The stored value is already normalized (e.g., AX-prefixed). */
({ literal: string }) & { glob?: never };

export type Modifiers = number;

export type Notification = string;

/**  host → pack */
export type PackHandlers = ({ runFunction: RunFunction }) & { accessibilityNotification?: never; endFunction?: never; renderView?: never; runViewAction?: never; workspaceAppActivated?: never; workspaceAppDeactivated?: never; workspaceAppTerminated?: never } | ({ endFunction: EndFunction }) & { accessibilityNotification?: never; renderView?: never; runFunction?: never; runViewAction?: never; workspaceAppActivated?: never; workspaceAppDeactivated?: never; workspaceAppTerminated?: never } | ({ accessibilityNotification: AccessibilityNotification }) & { endFunction?: never; renderView?: never; runFunction?: never; runViewAction?: never; workspaceAppActivated?: never; workspaceAppDeactivated?: never; workspaceAppTerminated?: never } | ({ workspaceAppActivated: WorkspaceAppActivated }) & { accessibilityNotification?: never; endFunction?: never; renderView?: never; runFunction?: never; runViewAction?: never; workspaceAppDeactivated?: never; workspaceAppTerminated?: never } | ({ workspaceAppDeactivated: WorkspaceAppDeactivated }) & { accessibilityNotification?: never; endFunction?: never; renderView?: never; runFunction?: never; runViewAction?: never; workspaceAppActivated?: never; workspaceAppTerminated?: never } | ({ workspaceAppTerminated: WorkspaceAppTerminated }) & { accessibilityNotification?: never; endFunction?: never; renderView?: never; runFunction?: never; runViewAction?: never; workspaceAppActivated?: never; workspaceAppDeactivated?: never } | ({ renderView: RenderView }) & { accessibilityNotification?: never; endFunction?: never; runFunction?: never; runViewAction?: never; workspaceAppActivated?: never; workspaceAppDeactivated?: never; workspaceAppTerminated?: never } | ({ runViewAction: RunViewAction }) & { accessibilityNotification?: never; endFunction?: never; renderView?: never; runFunction?: never; workspaceAppActivated?: never; workspaceAppDeactivated?: never; workspaceAppTerminated?: never };

export type RenderView = {
	view: View,
};

export type RunFunction = {
	function: Function,
	payload: JsonValue,
};

export type RunViewAction = {
	actionId: string,
	args: JsonValue,
	view: View,
};

export type SetAttributeValue = boolean | number | null | string;

export type View = number;

export type WorkspaceAppActivated = {
	app: AppHandle,
};

export type WorkspaceAppDeactivated = {
	app: AppHandle,
};

export type WorkspaceAppTerminated = {
	app: AppHandle,
};
